const getters = {
  token: state => state.user.token,
  name: state => state.user.name,
  avatar: state => state.user.avatar,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  accountChanged: state => state.user.accountChanged,
  isEzviz: state => state.user.isEzviz,
  authorities: state => state.user.authorities,
  permission_routes: state => state.user.routes,
  PatrolHistory: state => state.user.PatrolHistory,
  InspectHistory: state => state.user.InspectHistory,
  PatrolComment: state => state.user.PatrolComment,
  videoAuthority: state => state.user.videoAuthority,
  roleId: state => state.user.roleId,
  availabePathList: state => state.user.availabePathList,
  collapsed: state => state.user.collapsed,
  templateOptions: state => state.user.templateOptions,
  curTemplateIndex: state => state.user.curTemplateIndex,
  storeCache: state => state.user.storeCache,
};
export default getters;
